"""Package-local, typed Edition 2027 SDK. No host implementation ships here."""


def facade_sources(package_id: str, revision: int, version: str, edition: str = "2027", *, implementation: bool = True, presentations: bool = True) -> dict[str, str]:
    if not implementation and not presentations:
        return {}
    root = f"res://rookframe/packages/{package_id}/sdk/"
    header = f"## Generated by Rookframe SDK {version}. Regenerate with `rookframe facade`.\n"
    sources = {
        "package_sdk_facade.gd": f'''extends RefCounted

const Rail = preload("{root}rail.gd")
const Rails = preload("{root}rails.gd")
const WindowButton = preload("{root}window_button.gd")
const ExtensionSurface = preload("{root}extension_surface.gd")
const SDK_EDITION := "{edition}"
const MINIMUM_REVISION := {revision}

var _host: Object
var _rails: Rails
## Package-scoped access to the workspace Rails.
var rails: Rails:
\tget:
\t\treturn _rails


func _init(host: Object) -> void:
\t_host = host
\t_rails = Rails.new(host)


## Stable Package identity, independent of builds and installations.
func package_id() -> String:
\treturn _host.PackageId()


## Current admitted resource root for this Package.
func package_root() -> String:
\treturn _host.PackageRoot()


## Current desktop, tablet or phone Presentation experience.
func presentation_experience() -> String:
\treturn _host.PresentationExperience()
''',
        "rails.gd": f'''extends RefCounted

const Rail = preload("{root}rail.gd")
var _left: Rail
var _right: Rail
## The left Rail's Package contribution slot.
var left: Rail:
\tget:
\t\treturn _left
## The right Rail's Package contribution slot.
var right: Rail:
\tget:
\t\treturn _right


func _init(host: Object) -> void:
\t_left = Rail.new(host, "left")
\t_right = Rail.new(host, "right")
''',
        "rail.gd": f'''extends RefCounted

const WindowButton = preload("{root}window_button.gd")
var _host: Object
var _side: String


func _init(host: Object, side: String) -> void:
\t_host = host
\t_side = side


## Add an authored window-opening entry in Package-local insertion order.
## Repeated registration of the same entry is idempotent in this Presentation.
## Rookframe owns opening, responsive placement, lifetime and diagnostics.
func push(entry: WindowButton) -> void:
\t_host.RegisterWindowButton(_side, entry.button_scene, entry.window.scene)
''',
        "window_button.gd": f'''extends Resource

const ExtensionSurface = preload("{root}extension_surface.gd")
## Authored Button scene, using the public UI Kit Theme and assets.
@export var button_scene: PackedScene
## The window to open when this entry is activated.
@export var window: ExtensionSurface
''',
        "extension_surface.gd": '''extends Resource

## Authored Control scene hosted by Rookframe's managed window.
## windows.open retains live content across close/reopen.
## windows.open_actor binds one Actor and releases the sheet on close or lost access.
@export var scene: PackedScene
''',
        "presentation.gd": f'''extends Control

const SDK = preload("{root}package_sdk_facade.gd")
## Bound automatically before compose().
var sdk: SDK


func compose_presentation(host: Object) -> Control:
\tsdk = SDK.new(host)
\tcompose()
\treturn self


## Override to register this Presentation's authored UI through the SDK.
func compose() -> void:
\tpass
''',
        "implementation.gd": f'''extends Node

const SDK = preload("{root}package_sdk_facade.gd")
## Available during start() in an installed World.
var sdk: SDK


func _ready() -> void:
\tif has_meta("rookframe_sdk"):
\t\tsdk = SDK.new(get_meta("rookframe_sdk"))
\t\tif not has_meta("rookframe_cleanup"):
\t\t\tstart()


## Override for Package setup. Godot owns the surrounding Node lifecycle.
func start() -> void:
\tpass
''',
    }
    if revision >= 4 or edition in ("2028", "2029"):
        from rookframe_sdk_ui import ui_sources
        sources.update(ui_sources(root))
        sdk = sources["package_sdk_facade.gd"]
        types = ("Contribution", "ContributionSlot", "Slots", "Feedback", "FeedbackMessage", "FeedbackAction", "Translations", "Cleanup", "DeviceExperience")
        import re
        def snake(name):
            return re.sub(r"(?<!^)(?=[A-Z])", "_", name).lower()
        sdk += "\n" + "\n".join(f'const {name} = preload("{root}{snake(name)}.gd")' for name in types) + "\n"
        for name, type_name in (("ui_root", "ContributionSlot"), ("slots", "Slots"), ("feedback", "Feedback"), ("translations", "Translations")):
            sdk += f"\nvar _{name}: {type_name}\nvar {name}: {type_name}:\n\tget:\n\t\treturn _{name}\n"
        sdk = sdk.replace("\t_rails = Rails.new(host)", '''\t_rails = Rails.new(host)
\t_ui_root = ContributionSlot.new(host, "ui-root")
\t_slots = Slots.new(host)
\t_feedback = Feedback.new(host)
\t_translations = Translations.new(host)''')
        if edition in ("2028", "2029"):
            sdk = sdk.replace("func presentation_experience() -> String:\n\treturn _host.PresentationExperience()",
                "func presentation_experience() -> DeviceExperience:\n\treturn DeviceExperience.new(_host.PresentationDevice())")
        sources["package_sdk_facade.gd"] = sdk
        for name in ("presentation.gd", "implementation.gd"):
            sources[name] += '''

func cleanup_world(completed: Callable) -> void:
\tcleanup(SDK.Cleanup.new(completed))

## Override when this executable root has World-specific cleanup.
func cleanup(operation: SDK.Cleanup) -> void:
\toperation.complete()
'''
    if (edition == "2027" and revision >= 5) or (edition == "2028" and revision >= 2) or edition == "2029":
        from rookframe_sdk_world import world_sources
        shared_actions = edition == "2029" and revision >= 2
        world = world_sources(root, shared_actions=shared_actions,
                              actor_inspection=edition == "2029" and revision >= 3)
        sources.update(world)
        sdk = sources["package_sdk_facade.gd"]
        for filename in world:
            type_name = "".join(word.capitalize() for word in filename[:-3].split("_"))
            sdk += f'\nconst {type_name} = preload("{root}{filename}")'
        sdk += "\n\nfunc context() -> WorldContext:\n\treturn WorldContext.new(_host.WorldContext())\n"
        for name, type_name in (("world_data", "WorldData"), ("actors", "Actors"),
                                ("system_records", "SystemRecords"), ("rooks", "Rooks"),
                                ("scenes", "Scenes"), ("content", "Content"), ("windows", "Windows"),
                                ("builder", "UnavailableCapability"), ("targeting", "Targeting" if shared_actions else "UnavailableCapability"),
                                ("dice", "UnavailableCapability")):
            sdk += f"\nvar _{name}: {type_name}\nvar {name}: {type_name}:\n\tget:\n\t\treturn _{name}\n"
            initialization = f"\n\t_{name} = {type_name}.new(host)"
            if type_name == "UnavailableCapability":
                initialization += f'\n\t_{name}.configure("{name}")'
            sdk = sdk.replace("\t_host = host", "\t_host = host" + initialization, 1)
        if shared_actions:
            sdk += "\nsignal world_changed\nfunc _world_changed() -> void:\n\tworld_changed.emit()\n"
            sdk = sdk.replace("\t_host = host", "\t_host = host\n\t_host.WorldChanged.connect(_world_changed)", 1)
        sources["package_sdk_facade.gd"] = sdk
    if (edition == "2027" and revision >= 6) or (edition == "2028" and revision >= 3) or edition == "2029":
        from rookframe_sdk_settings import settings_sources, implementation_callbacks
        settings = settings_sources(root, typed_lists=(edition == "2029" or revision >= (7 if edition == "2027" else 4)))
        sources.update(settings)
        sdk = sources["package_sdk_facade.gd"]
        for filename in settings:
            type_name = "".join(word.capitalize() for word in filename[:-3].split("_"))
            sdk += f'\nconst {type_name} = preload("{root}{filename}")'
        sdk += "\n\nvar _settings: Settings\nvar settings: Settings:\n\tget:\n\t\treturn _settings\n"
        sdk = sdk.replace("\t_host = host", "\t_host = host\n\t_settings = Settings.new(host)", 1)
        sources["package_sdk_facade.gd"] = sdk
        sources["implementation.gd"] += implementation_callbacks()
        sources["presentation.gd"] += '''

## Optional Presentation-specific form inside Rookframe's settings menu.
@export var settings_view: SDK.SettingsViewDefinition
func _rookframe_settings_view() -> PackedScene:
\treturn settings_view.scene if settings_view != null else null
'''
    if edition == "2029":
        from rookframe_sdk_services import service_sources
        services = service_sources(root)
        sources.update(services)
        sources["secret_setting.gd"] += f'''
const AuthenticationProviderDefinition = preload("{root}authentication_provider_definition.gd")
## Optional provider for Rookframe-owned sign-in/refresh/clear controls.
@export var authentication: AuthenticationProviderDefinition
'''
        sdk = sources["package_sdk_facade.gd"]
        for filename in services:
            if filename == "service_scope.gd":
                continue
            type_name = "".join(word.capitalize() for word in filename[:-3].split("_"))
            sdk += f'\nconst {type_name} = preload("{root}{filename}")'
        sdk += f'\nconst ServiceScope = preload("{root}service_scope.gd")\nvar _service_scope: ServiceScope\n'
        for name, type_name in (("files", "Files"), ("clipboard", "Clipboard"), ("network", "Network"),
                                ("secrets", "Secrets"), ("authentication", "Authentication"), ("browser", "Browser")):
            sdk += f"\nvar _{name}: {type_name}\nvar {name}: {type_name}:\n\tget:\n\t\treturn _{name}\n"
            sdk = sdk.replace("\t_host = host", f"\t_host = host\n\t_{name} = {type_name}.new(_service_scope)", 1)
        sdk = sdk.replace("\t_host = host", "\t_host = host\n\t_service_scope = ServiceScope.new(host)", 1)
        sources["package_sdk_facade.gd"] = sdk
    if edition == "2029" and revision >= 3:
        sources["window.gd"] += '''

## Rookframe delivers the requested Actor on every explicit inspection.
func _rookframe_open_actor(actor_id: String) -> void:
\topened(SDK.ActorId.new(actor_id))

## Query this Actor through sdk.actors.read(actor) and render the returned data.
func opened(actor: SDK.ActorId) -> void:
\tpass
'''
    if not implementation:
        sources.pop("implementation.gd", None)
    if not presentations:
        sources.pop("presentation.gd", None)
    return {name: header + source for name, source in sources.items()}
