## Generated by Rookframe SDK 0.13.0. Regenerate with `rookframe facade`.
extends RefCounted

const ActorId = preload("res://rookframe/packages/dddddddd-dddd-4ddd-8ddd-dddddddddddd/sdk/actor_id.gd")
var id: ActorId
var data: Variant
var access_level: String
func _init(value: Dictionary) -> void:
	id = ActorId.new(value.id)
	data = value.data
	access_level = value.access_level
