## Generated by Rookframe SDK 0.13.0. Regenerate with `rookframe facade`.
extends "res://rookframe/packages/dddddddd-dddd-4ddd-8ddd-dddddddddddd/sdk/setting.gd"
const Setting = preload("res://rookframe/packages/dddddddd-dddd-4ddd-8ddd-dddddddddddd/sdk/setting.gd")
@export var item: Setting
