## Generated by Rookframe SDK 0.9.2. Regenerate with `rookframe facade`.
extends Resource

## Authored Control scene hosted by Rookframe's managed window.
## Its live content is retained across close/reopen and Presentation changes.
@export var scene: PackedScene
