## Generated by Rookframe SDK 0.13.1. Regenerate with `rookframe facade`.
extends Resource

const FeedbackAction = preload("res://rookframe/packages/dddddddd-dddd-4ddd-8ddd-dddddddddddd/sdk/feedback_action.gd")
@export var title: String
@export_multiline var message: String
@export var actions: Array[FeedbackAction] = []
