## Generated by Rookframe SDK 0.13.1. Regenerate with `rookframe facade`.
extends "res://rookframe/packages/dddddddd-dddd-4ddd-8ddd-dddddddddddd/sdk/setting.gd"
@export var default_value: int = 0
@export var minimum: int = -1000000
@export var maximum: int = 1000000
