## Generated by Rookframe SDK 0.13.1. Regenerate with `rookframe facade`.
extends RefCounted
const ServiceScope = preload("res://rookframe/packages/dddddddd-dddd-4ddd-8ddd-dddddddddddd/sdk/service_scope.gd")
const ServiceDefinition = preload("res://rookframe/packages/dddddddd-dddd-4ddd-8ddd-dddddddddddd/sdk/service_definition.gd")
const NamedService = preload("res://rookframe/packages/dddddddd-dddd-4ddd-8ddd-dddddddddddd/sdk/named_service.gd")
const Account = preload("res://rookframe/packages/dddddddd-dddd-4ddd-8ddd-dddddddddddd/sdk/account.gd")

var _scope: ServiceScope
func _init(scope: ServiceScope) -> void:
	_scope = scope
func service(definition: ServiceDefinition, account: Account = null) -> NamedService:
	return NamedService.new(_scope, definition.name, account)
