## Generated by Rookframe SDK 0.3.0. Regenerate with `rookframe facade`.
extends RefCounted

const Rail = preload("res://rookframe/packages/dddddddd-dddd-4ddd-8ddd-dddddddddddd/sdk/rail.gd")
const Rails = preload("res://rookframe/packages/dddddddd-dddd-4ddd-8ddd-dddddddddddd/sdk/rails.gd")
const WindowButton = preload("res://rookframe/packages/dddddddd-dddd-4ddd-8ddd-dddddddddddd/sdk/window_button.gd")
const ExtensionSurface = preload("res://rookframe/packages/dddddddd-dddd-4ddd-8ddd-dddddddddddd/sdk/extension_surface.gd")
const SDK_EDITION := "2027"
const MINIMUM_REVISION := 4

var _host: Object
var _rails: Rails
## Package-scoped access to the workspace Rails.
var rails: Rails:
	get:
		return _rails


func _init(host: Object) -> void:
	_host = host
	_rails = Rails.new(host)
	_ui_root = ContributionSlot.new(host, "ui-root")
	_slots = Slots.new(host)
	_feedback = Feedback.new(host)
	_translations = Translations.new(host)


## Stable Package identity, independent of builds and installations.
func package_id() -> String:
	return _host.PackageId()


## Current admitted resource root for this Package.
func package_root() -> String:
	return _host.PackageRoot()


## Current desktop, tablet or phone Presentation experience.
func presentation_experience() -> String:
	return _host.PresentationExperience()

const Contribution = preload("res://rookframe/packages/dddddddd-dddd-4ddd-8ddd-dddddddddddd/sdk/contribution.gd")
const ContributionSlot = preload("res://rookframe/packages/dddddddd-dddd-4ddd-8ddd-dddddddddddd/sdk/contribution_slot.gd")
const Slots = preload("res://rookframe/packages/dddddddd-dddd-4ddd-8ddd-dddddddddddd/sdk/slots.gd")
const Feedback = preload("res://rookframe/packages/dddddddd-dddd-4ddd-8ddd-dddddddddddd/sdk/feedback.gd")
const FeedbackMessage = preload("res://rookframe/packages/dddddddd-dddd-4ddd-8ddd-dddddddddddd/sdk/feedback_message.gd")
const FeedbackAction = preload("res://rookframe/packages/dddddddd-dddd-4ddd-8ddd-dddddddddddd/sdk/feedback_action.gd")
const Translations = preload("res://rookframe/packages/dddddddd-dddd-4ddd-8ddd-dddddddddddd/sdk/translations.gd")
const Cleanup = preload("res://rookframe/packages/dddddddd-dddd-4ddd-8ddd-dddddddddddd/sdk/cleanup.gd")
const DeviceExperience = preload("res://rookframe/packages/dddddddd-dddd-4ddd-8ddd-dddddddddddd/sdk/device_experience.gd")

var _ui_root: ContributionSlot
var ui_root: ContributionSlot:
	get:
		return _ui_root

var _slots: Slots
var slots: Slots:
	get:
		return _slots

var _feedback: Feedback
var feedback: Feedback:
	get:
		return _feedback

var _translations: Translations
var translations: Translations:
	get:
		return _translations
