## Generated by Rookframe SDK 0.3.0. Regenerate with `rookframe facade`.
extends Control

const SDK = preload("res://rookframe/packages/dddddddd-dddd-4ddd-8ddd-dddddddddddd/sdk/package_sdk_facade.gd")
## Bound automatically before compose().
var sdk: SDK


func compose_presentation(host: Object) -> Control:
	sdk = SDK.new(host)
	compose()
	return self


## Override to register this Presentation's authored UI through the SDK.
func compose() -> void:
	pass


func cleanup_world(completed: Callable) -> void:
	cleanup(SDK.Cleanup.new(completed))

## Override when this executable root has World-specific cleanup.
func cleanup(operation: SDK.Cleanup) -> void:
	operation.complete()
