## Generated by Rookframe SDK 0.13.1. Regenerate with `rookframe facade`.
extends RefCounted

const WorldCapability = preload("res://rookframe/packages/dddddddd-dddd-4ddd-8ddd-dddddddddddd/sdk/world_capability.gd")
const RookId = preload("res://rookframe/packages/dddddddd-dddd-4ddd-8ddd-dddddddddddd/sdk/rook_id.gd")
const ActorId = preload("res://rookframe/packages/dddddddd-dddd-4ddd-8ddd-dddddddddddd/sdk/actor_id.gd")
const RookResult = preload("res://rookframe/packages/dddddddd-dddd-4ddd-8ddd-dddddddddddd/sdk/rook_result.gd")
const RookListResult = preload("res://rookframe/packages/dddddddd-dddd-4ddd-8ddd-dddddddddddd/sdk/rook_list_result.gd")
const SceneId = preload("res://rookframe/packages/dddddddd-dddd-4ddd-8ddd-dddddddddddd/sdk/scene_id.gd")
const ContentReference = preload("res://rookframe/packages/dddddddd-dddd-4ddd-8ddd-dddddddddddd/sdk/content_reference.gd")
const OperationResult = preload("res://rookframe/packages/dddddddd-dddd-4ddd-8ddd-dddddddddddd/sdk/operation_result.gd")

var _host: Object
func _init(host: Object) -> void:
	_host = host

func list() -> RookListResult:
	return RookListResult.new(_host.ListRooks())
func read(id: RookId) -> RookResult:
	return RookResult.new(_host.ReadRook(id.value))
func create(miniature: ContentReference, scene: SceneId, position: Vector2, yaw: float = 0.0) -> RookResult:
	return RookResult.new(await WorldCapability.new().complete(_host, _host.CreateRook(miniature.package_id, miniature.local_id, scene.value, position, yaw)))
func move(id: RookId, position: Vector2, yaw: float = 0.0) -> RookResult:
	return RookResult.new(await WorldCapability.new().complete(_host, _host.MoveRook(id.value, position, yaw)))
func link(id: RookId, actor: ActorId) -> OperationResult:
	return OperationResult.new(await WorldCapability.new().complete(_host, _host.LinkRook(id.value, actor.value)))
func unlink(id: RookId) -> OperationResult:
	return OperationResult.new(await WorldCapability.new().complete(_host, _host.UnlinkRook(id.value)))
func delete(id: RookId) -> OperationResult:
	return OperationResult.new(await WorldCapability.new().complete(_host, _host.DeleteRook(id.value)))

## This Participant's local selection; it conveys no Actor Access.
func selected() -> RookId:
	var context: Dictionary = _host.SelectedRookContext()
	var id: String = context.get("id", "")
	return RookId.new(id) if id != "" else null
