## Generated by Rookframe SDK 0.13.0. Regenerate with `rookframe facade`.
extends RefCounted

const WorldCapability = preload("res://rookframe/packages/dddddddd-dddd-4ddd-8ddd-dddddddddddd/sdk/world_capability.gd")
const RookId = preload("res://rookframe/packages/dddddddd-dddd-4ddd-8ddd-dddddddddddd/sdk/rook_id.gd")
const SceneResult = preload("res://rookframe/packages/dddddddd-dddd-4ddd-8ddd-dddddddddddd/sdk/scene_result.gd")
const DistanceResult = preload("res://rookframe/packages/dddddddd-dddd-4ddd-8ddd-dddddddddddd/sdk/distance_result.gd")

var _host: Object
func _init(host: Object) -> void:
	_host = host

func current() -> SceneResult:
	return SceneResult.new(_host.CurrentScene())
func distance(from: RookId, to: RookId) -> DistanceResult:
	return DistanceResult.new(_host.RookDistance(from.value, to.value))
