## Generated by Rookframe SDK 0.13.1. Regenerate with `rookframe facade`.
extends RefCounted

const SceneId = preload("res://rookframe/packages/dddddddd-dddd-4ddd-8ddd-dddddddddddd/sdk/scene_id.gd")
var id: SceneId
var name: String
func _init(value: Dictionary) -> void:
	id = SceneId.new(value.id)
	name = value.name
