## Generated by Rookframe SDK 0.13.0. Regenerate with `rookframe facade`.
extends "res://rookframe/packages/dddddddd-dddd-4ddd-8ddd-dddddddddddd/sdk/setting.gd"
## Values use the existing protected store and never enter an ordinary draft/copy.

const AuthenticationProviderDefinition = preload("res://rookframe/packages/dddddddd-dddd-4ddd-8ddd-dddddddddddd/sdk/authentication_provider_definition.gd")
## Optional provider for Rookframe-owned sign-in/refresh/clear controls.
@export var authentication: AuthenticationProviderDefinition
