## Generated by Rookframe SDK 0.5.0. Regenerate with `rookframe facade`.
extends RefCounted

const ContributionSlot = preload("res://rookframe/packages/dddddddd-dddd-4ddd-8ddd-dddddddddddd/sdk/contribution_slot.gd")
var _selected_rook: ContributionSlot
var _actor_creation: ContributionSlot
var selected_rook: ContributionSlot:
	get:
		return _selected_rook
## Only the selected System Extension may contribute Actor Creation UI.
var actor_creation: ContributionSlot:
	get:
		return _actor_creation

func _init(host: Object) -> void:
	_selected_rook = ContributionSlot.new(host, "selected-rook")
	_actor_creation = ContributionSlot.new(host, "actor-creation")
