## Generated by Rookframe SDK 0.13.0. Regenerate with `rookframe facade`.
extends "res://rookframe/packages/dddddddd-dddd-4ddd-8ddd-dddddddddddd/sdk/setting.gd"
@export var default_value: String = ""
@export var choices: PackedStringArray = []
@export var minimum_length: int = 0
@export var maximum_length: int = 4096
