## Generated by Rookframe SDK 0.13.0. Regenerate with `rookframe facade`.
extends "res://rookframe/packages/dddddddd-dddd-4ddd-8ddd-dddddddddddd/sdk/setting.gd"
@export var default_value: PackedStringArray = []
@export var minimum_items: int = 0
@export var maximum_items: int = 256
@export var minimum_length: int = 0
@export var maximum_length: int = 4096
