## Generated by Rookframe SDK 0.13.1. Regenerate with `rookframe facade`.
extends RefCounted

const WorldCapability = preload("res://rookframe/packages/dddddddd-dddd-4ddd-8ddd-dddddddddddd/sdk/world_capability.gd")
const OperationResult = preload("res://rookframe/packages/dddddddd-dddd-4ddd-8ddd-dddddddddddd/sdk/operation_result.gd")

var _host: Object
func _init(host: Object) -> void:
	_host = host

var _capability: String
func configure(name: String) -> void:
	_capability = name
## Integration boundary reserved for the owning project; no predicted gameplay result.
func status() -> OperationResult:
	return OperationResult.new(_host.CapabilityStatus(_capability))
