## Generated by Rookframe SDK 0.5.0. Regenerate with `rookframe facade`.
extends Control

const SDK = preload("res://rookframe/packages/dddddddd-dddd-4ddd-8ddd-dddddddddddd/sdk/package_sdk_facade.gd")
## Bound by Rookframe before the authored window enters the tree. Null in the standalone editor.
var sdk: SDK

func _ready() -> void:
	if has_meta("rookframe_sdk"):
		sdk = SDK.new(get_meta("rookframe_sdk"))
	ready()

## Override for authored view setup; normal Godot child readiness has completed.
func ready() -> void:
	pass
