## Generated by Rookframe SDK 0.13.1. Regenerate with `rookframe facade`.
extends "res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/integration_result.gd"
enum State { UNAVAILABLE, SIGNED_OUT, SIGNED_IN, EXPIRED }
var state: State
func _init(result: Dictionary) -> void:
	super(result)
	state = result.get("state", State.UNAVAILABLE)
