## Generated by Rookframe SDK 0.15.0. Regenerate with `rookframe facade`.
extends Resource

const ActionLogText = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/action_log_text.gd")
const ActionLogDie = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/action_log_die.gd")
@export var title: String
@export var text: Array[ActionLogText] = []
@export var dice: Array[ActionLogDie] = []
@export var result: String = ""
## info, success, attention, or roll. Meaning belongs to the caller.
@export var tone: String = "info"
func _init(heading: String = "") -> void:
	title = heading
func to_record() -> Dictionary:
	var runs: Array = []
	var faces: Array = []
	for run in text:
		if run == null:
			runs.append(null)
		else:
			runs.append({"text": run.text, "style": run.style})
	for die in dice:
		if die == null:
			faces.append(null)
		else:
			faces.append({"sides": die.sides, "value": die.value})
	return {"title": title, "text": runs, "dice": faces, "result": result, "tone": tone}
