## Generated by Rookframe SDK 0.13.1. Regenerate with `rookframe facade`.
extends RefCounted

const ActionLogMessage = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/action_log_message.gd")
const ActionLogResult = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/action_log_result.gd")
const WorldCapability = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/world_capability.gd")
var _host: Object
func _init(host: Object) -> void:
	_host = host
## Await authority acceptance and broadcast. The host supplies Participant and Package attribution.
func publish(message: ActionLogMessage) -> ActionLogResult:
	var record: Dictionary = {} if message == null else message.to_record()
	return ActionLogResult.new(await WorldCapability.new().complete(_host, _host.PublishActionLog(record)))
