## Generated by Rookframe SDK 0.4.0. Regenerate with `rookframe facade`.
extends RefCounted

const ActorId = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/actor_id.gd")
const ActorResult = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/actor_result.gd")
const ActorListResult = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/actor_list_result.gd")
const ContentReference = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/content_reference.gd")
const OperationResult = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/operation_result.gd")

var _host: Object
func _init(host: Object) -> void:
	_host = host

func list() -> ActorListResult:
	return ActorListResult.new(_host.ListActors())
func read(id: ActorId) -> ActorResult:
	return ActorResult.new(_host.ReadActor(id.value))
func create(definition: ContentReference, choices: Variant) -> ActorResult:
	return ActorResult.new(_host.CreateActor(definition.package_id, definition.local_id, choices))
func update(id: ActorId, data: Variant) -> ActorResult:
	return ActorResult.new(_host.UpdateActor(id.value, data))
func delete(id: ActorId) -> OperationResult:
	return OperationResult.new(_host.DeleteActor(id.value))
