## Generated by Rookframe SDK 0.16.0. Regenerate with `rookframe facade`.
extends RefCounted

## Presentation-only identity for Rookframe's native Actor list.
var display_name: String
var portrait: Texture2D
func _init(name: String = "", image: Texture2D = null) -> void:
	display_name = name
	portrait = image
