## Generated by Rookframe SDK 0.16.0. Regenerate with `rookframe facade`.
extends RefCounted
var participant_id: String
var display_name: String
var access_level: String
var is_connected: bool
func _init(value: Dictionary) -> void:
	participant_id = value.participant_id
	display_name = value.display_name
	access_level = value.access_level
	is_connected = value.get("is_connected", false)
