## Generated by Rookframe SDK 0.13.1. Regenerate with `rookframe facade`.
extends RefCounted

const WorldCapability = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/world_capability.gd")
const ActorId = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/actor_id.gd")
const ActorResult = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/actor_result.gd")
const ActorListResult = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/actor_list_result.gd")
const ContentReference = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/content_reference.gd")
const OperationResult = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/operation_result.gd")

var _host: Object
func _init(host: Object) -> void:
	_host = host

const ActorAccessListResult = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/actor_access_list_result.gd")

func list() -> ActorListResult:
	return ActorListResult.new(_host.ListActors())
func read(id: ActorId) -> ActorResult:
	return ActorResult.new(_host.ReadActor(id.value))
func create(definition: ContentReference, choices: Variant) -> ActorResult:
	return ActorResult.new(await WorldCapability.new().complete(_host, _host.CreateActor(definition.package_id, definition.local_id, choices)))
func update(id: ActorId, data: Variant) -> ActorResult:
	return ActorResult.new(await WorldCapability.new().complete(_host, _host.UpdateActor(id.value, data)))
func delete(id: ActorId) -> OperationResult:
	return OperationResult.new(await WorldCapability.new().complete(_host, _host.DeleteActor(id.value)))

func access(id: ActorId) -> ActorAccessListResult:
	return ActorAccessListResult.new(_host.ListActorAccess(id.value))
func set_access(id: ActorId, participant: String, level: String) -> OperationResult:
	return OperationResult.new(await WorldCapability.new().complete(_host, _host.SetActorAccess(id.value, participant, level)))
