## Generated by Rookframe SDK 0.11.0. Regenerate with `rookframe facade`.
extends RefCounted

const ActorId = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/actor_id.gd")
var id: ActorId
var data: Variant
var access_level: String
func _init(value: Dictionary) -> void:
	id = ActorId.new(value.id)
	data = value.data
	access_level = value.access_level
