## Generated by Rookframe SDK 0.9.1. Regenerate with `rookframe facade`.
extends "res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/setting.gd"
const Setting = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/setting.gd")
@export var item: Setting
