## Generated by Rookframe SDK 0.5.0. Regenerate with `rookframe facade`.
extends RefCounted

var _completed: Callable
var _finished := false

func _init(completed: Callable) -> void:
	_completed = completed

## Acknowledge immediate or asynchronous cleanup within the shared one-second deadline.
func complete() -> void:
	if not _finished:
		_finished = true
		_completed.call()
