## Generated by Rookframe SDK 0.9.2. Regenerate with `rookframe facade`.
extends Resource

## Stable Package/local identity. Never a build path or a Package version.
@export var package_id: String
@export var local_id: String
func _init(package: String = "", item: String = "") -> void:
	package_id = package
	local_id = item
