## Generated by Rookframe SDK 0.14.0. Regenerate with `rookframe facade`.
extends RefCounted

const DiceRequest = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/dice_request.gd")
const DiceRollResult = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/dice_roll_result.gd")
const WorldCapability = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/world_capability.gd")
var _host: Object
func _init(host: Object) -> void:
	_host = host
## Physically roll now and await the committed raw named result.
func roll(request: DiceRequest) -> DiceRollResult:
	var terms: Array = [] if request == null else request.to_records()
	return DiceRollResult.new(await WorldCapability.new().complete(_host, _host.RollDice(terms)))
