## Generated by Rookframe SDK 0.16.0. Regenerate with `rookframe facade`.
extends Resource

const DiceTerm = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/dice_term.gd")
## Terms retain this order. Their total count may not exceed sixteen dice.
@export var terms: Array[DiceTerm] = []
func _init(requested_terms: Array[DiceTerm] = []) -> void:
	terms = requested_terms
func to_records() -> Array:
	var records: Array = []
	for term in terms:
		records.append({} if term == null else term.to_record())
	return records
