## Generated by Rookframe SDK 0.16.0. Regenerate with `rookframe facade`.
extends Resource

## Package-owned name for one raw pool term. Rookframe does not interpret it.
@export var name: String
@export var faces: int
@export var count: int = 1
func _init(term_name: String = "", face_count: int = 6, dice_count: int = 1) -> void:
	name = term_name
	faces = face_count
	count = dice_count
func to_record() -> Dictionary:
	return {"name": name, "faces": faces, "count": count}
