## Generated by Rookframe SDK 0.16.0. Regenerate with `rookframe facade`.
extends Resource

## Authored Control scene hosted by Rookframe's managed window.
## windows.open retains live content across close/reopen.
## windows.open_actor binds one Actor and releases the sheet on close or lost access.
@export var scene: PackedScene
## First-open placement. The Participant can move or redock the retained window.
@export var initial_placement := "right"
## Optional first-open dock width in logical pixels. Zero uses Rookframe's responsive default.
@export var initial_dock_width := 0.0
## Optional first-open floating geometry. An empty Rect2 uses Rookframe's responsive default.
@export var initial_floating_rect: Rect2


func initial_presentation() -> Dictionary:
	return {
		"placement": initial_placement,
		"dockWidth": initial_dock_width,
		"floatingRect": initial_floating_rect,
	}
