## Generated by Rookframe SDK 0.13.0. Regenerate with `rookframe facade`.
extends Resource

## Authored Control scene hosted by Rookframe's managed window.
## windows.open retains live content across close/reopen.
## windows.open_actor binds one Actor and releases the sheet on close or lost access.
@export var scene: PackedScene
