## Generated by Rookframe SDK 0.10.0. Regenerate with `rookframe facade`.
extends RefCounted

const FeedbackMessage = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/feedback_message.gd")
signal action_selected(action: String)
var _request_id: int = 0
var _host: Object

func _init(host: Object) -> void:
	_host = host
	_host.connect("FeedbackActionSelected", _on_action)

func notice(message: FeedbackMessage) -> void:
	_show(message, "notice")

func warning(message: FeedbackMessage) -> void:
	_show(message, "warning")

func error(message: FeedbackMessage) -> void:
	_show(message, "error")

func confirm(message: FeedbackMessage) -> void:
	_show(message, "confirmation")

func _show(message: FeedbackMessage, severity: String) -> void:
	var actions: Array[Dictionary] = []
	for action in message.actions:
		actions.append({"id": action.id, "title": action.title})
	_request_id = _host.ShowFeedback(message.title, message.message, severity, actions)

func _on_action(request_id: int, action: String) -> void:
	if request_id == _request_id:
		action_selected.emit(action)
