## Generated by Rookframe SDK 0.14.0. Regenerate with `rookframe facade`.
extends Resource

const FeedbackAction = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/feedback_action.gd")
@export var title: String
@export_multiline var message: String
@export var actions: Array[FeedbackAction] = []
