## Generated by Rookframe SDK 0.15.0. Regenerate with `rookframe facade`.
extends RefCounted
const ServiceScope = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/service_scope.gd")
const ScopedFile = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/scoped_file.gd")
const ScopedFolder = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/scoped_folder.gd")

var _scope: ServiceScope
var _area: String
func _init(scope: ServiceScope, area: String) -> void:
	_scope = scope
	_area = area
## Relative names are validated by the host on each use. A value grants no new authority.
func file(relative_name: String) -> ScopedFile:
	return ScopedFile.new(_scope, _area, relative_name)
func folder(relative_name: String) -> ScopedFolder:
	return ScopedFolder.new(_scope, _area, relative_name)
const FileSelectionResult = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/file_selection_result.gd")

func select_file() -> FileSelectionResult:
	var result: Dictionary = await _scope._complete(_scope._host.SelectFile(_area, false))
	var selected: ScopedFile
	if result.get("ok", false):
		selected = ScopedFile.new(_scope, _area, result.get("text", ""))
	return FileSelectionResult.new(result, selected)
const FolderSelectionResult = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/folder_selection_result.gd")

func select_folder() -> FolderSelectionResult:
	var result: Dictionary = await _scope._complete(_scope._host.SelectFile(_area, true))
	var selected: ScopedFolder
	if result.get("ok", false):
		selected = ScopedFolder.new(_scope, _area, result.get("text", ""))
	return FolderSelectionResult.new(result, selected)
