## Generated by Rookframe SDK 0.12.0. Regenerate with `rookframe facade`.
extends "res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/setting.gd"
@export var default_value: float = 0.0
@export var minimum: float = -1000000
@export var maximum: float = 1000000
