## Generated by Rookframe SDK 0.9.1. Regenerate with `rookframe facade`.
extends RefCounted

const Rail = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/rail.gd")
const Rails = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/rails.gd")
const WindowButton = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/window_button.gd")
const ExtensionSurface = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/extension_surface.gd")
const SDK_EDITION := "2028"
const MINIMUM_REVISION := 3

var _host: Object
var _rails: Rails
## Package-scoped access to the workspace Rails.
var rails: Rails:
	get:
		return _rails


func _init(host: Object) -> void:
	_host = host
	_settings = Settings.new(host)
	_dice = UnavailableCapability.new(host)
	_dice.configure("dice")
	_targeting = UnavailableCapability.new(host)
	_targeting.configure("targeting")
	_builder = UnavailableCapability.new(host)
	_builder.configure("builder")
	_windows = Windows.new(host)
	_content = Content.new(host)
	_scenes = Scenes.new(host)
	_rooks = Rooks.new(host)
	_system_records = SystemRecords.new(host)
	_actors = Actors.new(host)
	_world_data = WorldData.new(host)
	_rails = Rails.new(host)
	_ui_root = ContributionSlot.new(host, "ui-root")
	_slots = Slots.new(host)
	_feedback = Feedback.new(host)
	_translations = Translations.new(host)


## Stable Package identity, independent of builds and installations.
func package_id() -> String:
	return _host.PackageId()


## Current admitted resource root for this Package.
func package_root() -> String:
	return _host.PackageRoot()


## Current desktop, tablet or phone Presentation experience.
func presentation_experience() -> DeviceExperience:
	return DeviceExperience.new(_host.PresentationDevice())

const Contribution = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/contribution.gd")
const ContributionSlot = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/contribution_slot.gd")
const Slots = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/slots.gd")
const Feedback = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/feedback.gd")
const FeedbackMessage = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/feedback_message.gd")
const FeedbackAction = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/feedback_action.gd")
const Translations = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/translations.gd")
const Cleanup = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/cleanup.gd")
const DeviceExperience = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/device_experience.gd")

var _ui_root: ContributionSlot
var ui_root: ContributionSlot:
	get:
		return _ui_root

var _slots: Slots
var slots: Slots:
	get:
		return _slots

var _feedback: Feedback
var feedback: Feedback:
	get:
		return _feedback

var _translations: Translations
var translations: Translations:
	get:
		return _translations

const OperationResult = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/operation_result.gd")
const DataResult = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/data_result.gd")
const WorldContext = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/world_context.gd")
const WorldData = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/world_data.gd")
const ContentReference = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/content_reference.gd")
const ActorDefinition = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/actor_definition.gd")
const UnavailableCapability = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/unavailable_capability.gd")
const ActorId = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/actor_id.gd")
const SystemRecordId = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/system_record_id.gd")
const RookId = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/rook_id.gd")
const SceneId = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/scene_id.gd")
const Actor = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/actor.gd")
const ActorResult = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/actor_result.gd")
const ActorListResult = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/actor_list_result.gd")
const SystemRecord = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/system_record.gd")
const SystemRecordResult = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/system_record_result.gd")
const SystemRecordListResult = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/system_record_list_result.gd")
const Rook = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/rook.gd")
const RookResult = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/rook_result.gd")
const RookListResult = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/rook_list_result.gd")
const Scene = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/scene.gd")
const SceneResult = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/scene_result.gd")
const ContentEntry = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/content_entry.gd")
const ContentEntryResult = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/content_entry_result.gd")
const ContentEntryListResult = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/content_entry_list_result.gd")
const Actors = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/actors.gd")
const SystemRecords = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/system_records.gd")
const Rooks = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/rooks.gd")
const DistanceResult = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/distance_result.gd")
const Scenes = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/scenes.gd")
const Content = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/content.gd")
const ContentKind = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/content_kind.gd")
const Windows = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/windows.gd")

func context() -> WorldContext:
	return WorldContext.new(_host.WorldContext())

var _world_data: WorldData
var world_data: WorldData:
	get:
		return _world_data

var _actors: Actors
var actors: Actors:
	get:
		return _actors

var _system_records: SystemRecords
var system_records: SystemRecords:
	get:
		return _system_records

var _rooks: Rooks
var rooks: Rooks:
	get:
		return _rooks

var _scenes: Scenes
var scenes: Scenes:
	get:
		return _scenes

var _content: Content
var content: Content:
	get:
		return _content

var _windows: Windows
var windows: Windows:
	get:
		return _windows

var _builder: UnavailableCapability
var builder: UnavailableCapability:
	get:
		return _builder

var _targeting: UnavailableCapability
var targeting: UnavailableCapability:
	get:
		return _targeting

var _dice: UnavailableCapability
var dice: UnavailableCapability:
	get:
		return _dice

const SettingsScope = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/settings_scope.gd")
const Setting = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/setting.gd")
const TextSetting = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/text_setting.gd")
const SecretSetting = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/secret_setting.gd")
const SettingsRegistration = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/settings_registration.gd")
const SettingsValidation = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/settings_validation.gd")
const ToggleSetting = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/toggle_setting.gd")
const IntegerSetting = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/integer_setting.gd")
const NumberSetting = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/number_setting.gd")
const ObjectSetting = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/object_setting.gd")
const ArraySetting = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/array_setting.gd")
const SettingsValues = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/settings_values.gd")
const SettingsDraft = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/settings_draft.gd")
const SettingsCandidate = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/settings_candidate.gd")
const SettingsMigration = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/settings_migration.gd")
const Settings = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/settings.gd")
const SettingsView = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/settings_view.gd")
const SettingsViewDefinition = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/settings_view_definition.gd")

var _settings: Settings
var settings: Settings:
	get:
		return _settings
