## Generated by Rookframe SDK 0.12.0. Regenerate with `rookframe facade`.
extends Control

const SDK = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/package_sdk_facade.gd")
## Bound automatically before compose().
var sdk: SDK


func compose_presentation(host: Object) -> Control:
	sdk = SDK.new(host)
	compose()
	return self


## Override to register this Presentation's authored UI through the SDK.
func compose() -> void:
	pass


func cleanup_world(completed: Callable) -> void:
	cleanup(SDK.Cleanup.new(completed))

## Override when this executable root has World-specific cleanup.
func cleanup(operation: SDK.Cleanup) -> void:
	operation.complete()


## Optional Presentation-specific form inside Rookframe's settings menu.
@export var settings_view: SDK.SettingsViewDefinition
func _rookframe_settings_view() -> PackedScene:
	return settings_view.scene if settings_view != null else null


## The selected System supplies identity; Rookframe owns listing and access.
func describe_actor(actor: SDK.Actor) -> SDK.ActorSummary:
	return SDK.ActorSummary.new()

## Called when a native Actor row is activated. Open a suitable Actor sheet.
func inspect_actor(actor: SDK.ActorId) -> void:
	pass

func _rookframe_describe_actor(actor_id: String) -> Dictionary:
	var result: SDK.ActorResult = sdk.actors.read(SDK.ActorId.new(actor_id))
	if not result.ok:
		return {}
	var summary: SDK.ActorSummary = describe_actor(result.actor)
	return {"displayName": summary.display_name, "portrait": summary.portrait}

func _rookframe_inspect_actor(actor_id: String) -> void:
	var actor: SDK.ActorId = SDK.ActorId.new(actor_id)
	if sdk.actors.read(actor).ok:
		inspect_actor(actor)
