## Generated by Rookframe SDK 0.6.0. Regenerate with `rookframe facade`.
extends Control

const SDK = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/package_sdk_facade.gd")
## Bound automatically before compose().
var sdk: SDK


func compose_presentation(host: Object) -> Control:
	sdk = SDK.new(host)
	compose()
	return self


## Override to register this Presentation's authored UI through the SDK.
func compose() -> void:
	pass


func cleanup_world(completed: Callable) -> void:
	cleanup(SDK.Cleanup.new(completed))

## Override when this executable root has World-specific cleanup.
func cleanup(operation: SDK.Cleanup) -> void:
	operation.complete()


## Optional Presentation-specific form inside Rookframe's settings menu.
@export var settings_view: SDK.SettingsViewDefinition
func _rookframe_settings_view() -> PackedScene:
	return settings_view.scene if settings_view != null else null
