## Generated by Rookframe SDK 0.16.0. Regenerate with `rookframe facade`.
extends RefCounted

const Rail = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/rail.gd")
var _left: Rail
var _right: Rail
## The left Rail's Package contribution slot.
var left: Rail:
	get:
		return _left
## The right Rail's Package contribution slot.
var right: Rail:
	get:
		return _right


func _init(host: Object) -> void:
	_left = Rail.new(host, "left")
	_right = Rail.new(host, "right")
