## Generated by Rookframe SDK 0.6.0. Regenerate with `rookframe facade`.
extends RefCounted

const SceneId = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/scene_id.gd")
var id: SceneId
var name: String
func _init(value: Dictionary) -> void:
	id = SceneId.new(value.id)
	name = value.name
