## Generated by Rookframe SDK 0.13.1. Regenerate with `rookframe facade`.
extends RefCounted
const ServiceScope = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/service_scope.gd")
const BytesResult = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/bytes_result.gd")
const IntegrationResult = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/integration_result.gd")

var _scope: ServiceScope
var _id: int
func _init(scope: ServiceScope, id: int) -> void:
	_scope = scope
	_id = id
func read(maximum_bytes: int = 65536) -> BytesResult:
	return BytesResult.new(await _scope._complete(_scope._host.ReadServiceStream(_id, maximum_bytes)))
func close() -> IntegrationResult:
	return IntegrationResult.new(_scope._host.CloseServiceStream(_id))
