## Generated by Rookframe SDK 0.11.0. Regenerate with `rookframe facade`.
extends RefCounted
const ServiceScope = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/service_scope.gd")
const ScopedFile = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/scoped_file.gd")

var _scope: ServiceScope
var _area: String
var _path: String
func _init(scope: ServiceScope, area: String, relative_name: String) -> void:
	_scope = scope
	_area = area
	_path = relative_name
func file(relative_name: String) -> ScopedFile:
	return ScopedFile.new(_scope, _area, (_path + "/" if not _path.is_empty() else "") + relative_name)
const FileLocation = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/file_location.gd")
const InternalFolderReference = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/internal_folder_reference.gd")

## Retain this value in Package-owned data to reopen through a fresh authorized SDK.
func to_reference() -> InternalFolderReference:
	return InternalFolderReference.new(FileLocation.new()._value(_area), _path)
