## Generated by Rookframe SDK 0.10.0. Regenerate with `rookframe facade`.
extends RefCounted
const ServiceScope = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/service_scope.gd")
const TextResult = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/text_result.gd")
const BytesResult = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/bytes_result.gd")
const IntegrationResult = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/integration_result.gd")

var _scope: ServiceScope
var _area: String
var _path: String
func _init(scope: ServiceScope, area: String, relative_name: String) -> void:
	_scope = scope
	_area = area
	_path = relative_name
func read_text() -> TextResult:
	return TextResult.new(_scope._host.ReadText(_area, _path))
func read_bytes() -> BytesResult:
	return BytesResult.new(_scope._host.ReadFile(_area, _path))
## Immutable Package content always refuses writes.
func write_text(text: String) -> IntegrationResult:
	return IntegrationResult.new(_scope._host.WriteText(_area, _path, text))
func write_bytes(data: PackedByteArray) -> IntegrationResult:
	return IntegrationResult.new(_scope._host.WriteFile(_area, _path, data))
const PortraitResult = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/portrait_result.gd")

func read_portrait() -> PortraitResult:
	return PortraitResult.new(_scope._host.DecodePortrait(_area, _path))
const FileLocation = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/file_location.gd")
const InternalFileReference = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/internal_file_reference.gd")

## Retain this value in Package-owned data to reopen through a fresh authorized SDK.
func to_reference() -> InternalFileReference:
	return InternalFileReference.new(FileLocation.new()._value(_area), _path)
