## Generated by Rookframe SDK 0.13.1. Regenerate with `rookframe facade`.
extends RefCounted
const ServiceScope = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/service_scope.gd")
const SecretResult = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/secret_result.gd")
const ProviderTokenResult = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/provider_token_result.gd")
const IntegrationResult = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/integration_result.gd")

var _scope: ServiceScope
var _area: String
var _entry: String
func _init(scope: ServiceScope, area: String, name: String) -> void:
	_scope = scope
	_area = area
	_entry = name
func read() -> SecretResult:
	return SecretResult.new(_scope._host.ReadSecret(_area, _entry))
func read_tokens() -> ProviderTokenResult:
	return ProviderTokenResult.new(_scope._host.ReadProviderTokens(_area, _entry))
func write(value: String) -> IntegrationResult:
	return IntegrationResult.new(_scope._host.WriteSecret(_area, _entry, value))
func clear() -> IntegrationResult:
	return IntegrationResult.new(_scope._host.RevokeSecret(_area, _entry))
