## Generated by Rookframe SDK 0.8.0. Regenerate with `rookframe facade`.
extends "res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/setting.gd"
## Values use the existing protected store and never enter an ordinary draft/copy.
