## Generated by Rookframe SDK 0.6.0. Regenerate with `rookframe facade`.
extends Resource
const Setting = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/setting.gd")
@export var user: Array[Setting] = []
@export var world: Array[Setting] = []
