## Generated by Rookframe SDK 0.8.0. Regenerate with `rookframe facade`.
extends "res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/settings_draft.gd"
const SettingsScope = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/settings_scope.gd")
var scope: SettingsScope.Kind
var source_version: String
var target_version: String
func _init(candidate_scope: SettingsScope.Kind, source: String, target: String, values: Dictionary) -> void:
	super(values)
	scope = candidate_scope
	source_version = source
	target_version = target
