## Generated by Rookframe SDK 0.9.2. Regenerate with `rookframe facade`.
extends Resource
enum Application { LIVE, RESTART_LOCAL, RESTART_WORLD }
## Stable Package-local name. Rookframe supplies the Package namespace.
## Application policy belongs to the containing setting; nested fields stay LIVE.
@export var key: String
@export var title: String
@export_multiline var description: String
@export var application: Application = Application.LIVE
