## Generated by Rookframe SDK 0.9.0. Regenerate with `rookframe facade`.
extends "res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/settings_values.gd"

func set_text(setting: TextSetting, value: String) -> void:
	_values[setting.key] = value

func set_toggle(setting: ToggleSetting, value: bool) -> void:
	_values[setting.key] = value

func set_integer(setting: IntegerSetting, value: int) -> void:
	_values[setting.key] = value

func set_number(setting: NumberSetting, value: float) -> void:
	_values[setting.key] = value

func set_object(setting: ObjectSetting, value: Dictionary) -> void:
	_values[setting.key] = value.duplicate(true)

func set_array(setting: ArraySetting, value: Array) -> void:
	_values[setting.key] = value.duplicate(true)
