## Generated by Rookframe SDK 0.15.0. Regenerate with `rookframe facade`.
extends RefCounted

const SystemRecordId = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/system_record_id.gd")
var id: SystemRecordId
var type_name: String
var data: Variant
func _init(value: Dictionary) -> void:
	id = SystemRecordId.new(value.id)
	type_name = value.type_name
	data = value.data
