## Generated by Rookframe SDK 0.14.0. Regenerate with `rookframe facade`.
extends RefCounted

const RookId = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/rook_id.gd")
const SceneId = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/scene_id.gd")

var participant_id: String
var session_id: String
var display_name: String
var scene: SceneId
var revision: int
var rooks: Array[RookId] = []
func _init(value: Dictionary) -> void:
	participant_id = value.participant_id
	session_id = value.session_id
	display_name = value.display_name
	scene = SceneId.new(value.scene_id)
	revision = value.revision
	var ids: PackedStringArray = value.rook_ids
	for id in ids:
		rooks.append(RookId.new(id))
