## Generated by Rookframe SDK 0.12.0. Regenerate with `rookframe facade`.
extends "res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/setting.gd"
@export var default_value: String = ""
@export var choices: PackedStringArray = []
@export var minimum_length: int = 0
@export var maximum_length: int = 4096
