## Generated by Rookframe SDK 0.9.1. Regenerate with `rookframe facade`.
extends RefCounted

const OperationResult = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/operation_result.gd")

var _host: Object
func _init(host: Object) -> void:
	_host = host

var _capability: String
func configure(name: String) -> void:
	_capability = name
## Integration boundary reserved for the owning project; no predicted gameplay result.
func status() -> OperationResult:
	return OperationResult.new(_host.CapabilityStatus(_capability))
