## Generated by Rookframe SDK 0.5.0. Regenerate with `rookframe facade`.
extends RefCounted

const ExtensionSurface = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/extension_surface.gd")

var _host: Object
func _init(host: Object) -> void:
	_host = host

func open(surface: ExtensionSurface) -> void:
	_host.OpenWindow(surface.scene)
