## Generated by Rookframe SDK 0.11.0. Regenerate with `rookframe facade`.
extends Control

const SDK = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/package_sdk_facade.gd")
## Bound by Rookframe before the authored window enters the tree. Null in the standalone editor.
var sdk: SDK

func _ready() -> void:
	if has_meta("rookframe_sdk"):
		sdk = SDK.new(get_meta("rookframe_sdk"))
	ready()

## Override for authored view setup; normal Godot child readiness has completed.
func ready() -> void:
	pass


## Rookframe delivers the requested Actor on every explicit inspection.
func _rookframe_open_actor(actor_id: String) -> void:
	opened(SDK.ActorId.new(actor_id))

## Query this Actor through sdk.actors.read(actor) and render the returned data.
func opened(actor: SDK.ActorId) -> void:
	pass
