## Generated by Rookframe SDK 0.10.0. Regenerate with `rookframe facade`.
extends Resource

const ExtensionSurface = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/extension_surface.gd")
## Authored Button scene, using the public UI Kit Theme and assets.
@export var button_scene: PackedScene
## The window to open when this entry is activated.
@export var window: ExtensionSurface
