## Generated by Rookframe SDK 0.14.0. Regenerate with `rookframe facade`.
extends RefCounted

const WorldCapability = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/world_capability.gd")
const ExtensionSurface = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/extension_surface.gd")

var _host: Object
func _init(host: Object) -> void:
	_host = host

func open(surface: ExtensionSurface) -> void:
	_host.OpenWindow(surface.scene)
const ActorId = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/actor_id.gd")
const OperationResult = preload("res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/operation_result.gd")


## Open this Actor's view and deliver its identity to Window.opened(actor).
## Rookframe closes Actor views when access is lost; ordinary UI stays authored.
func open_actor(surface: ExtensionSurface, actor: ActorId) -> OperationResult:
	return OperationResult.new(_host.OpenActorWindow(surface.scene, actor.value))
