## Generated by Rookframe SDK 0.16.0. Regenerate with `rookframe facade`.
extends RefCounted

## Stock Godot signal completion; callers await mutating operations.
func complete(host: Object, result: Dictionary) -> Dictionary:
	if result.get("code", "") != "pending":
		return result
	var request_id: int = result.requestId
	while true:
		var outcome: Dictionary = await host.TabletopCommandCompleted
		if outcome.requestId == request_id:
			return outcome
	return result
