## Generated by Rookframe SDK 0.9.0. Regenerate with `rookframe facade`.
extends "res://rookframe/packages/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/sdk/operation_result.gd"

var is_authority: bool = false
var is_gm: bool = false
var participant_id: String = ""
func _init(result: Dictionary) -> void:
	super(result)
	if ok:
		is_authority = result.value.is_authority
		is_gm = result.value.is_gm
		participant_id = result.value.participant_id
