## Generated by Rookframe SDK 0.9.2. Regenerate with `rookframe facade`.
extends RefCounted
const ServiceScope = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/service_scope.gd")
const IntegrationResult = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/integration_result.gd")
const ProviderTokenResult = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/provider_token_result.gd")
const AccountStatus = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/account_status.gd")

enum RefreshPolicy { EXPLICIT, WHEN_EXPIRED }
## Preflight refresh only. HTTP failures never replay a request or launch sign-in.
var refresh_policy: RefreshPolicy = RefreshPolicy.WHEN_EXPIRED
var _scope: ServiceScope
var _provider: String
var _area: String
var _entry: String
func _init(scope: ServiceScope, provider: String, area: String, entry: String) -> void:
	_scope = scope
	_provider = provider
	_area = area
	_entry = entry
func status() -> AccountStatus:
	return AccountStatus.new(_scope._host.AccountStatus(_provider, _area, _entry))
func read_tokens() -> ProviderTokenResult:
	return ProviderTokenResult.new(_scope._host.ReadAccountTokens(_provider, _area, _entry))
func sign_in() -> IntegrationResult:
	return IntegrationResult.new(await _scope._complete(_scope._host.StartAuthentication(_provider, _area, _entry), true))
func refresh() -> IntegrationResult:
	return IntegrationResult.new(await _scope._complete(_scope._host.RefreshSecret(_provider, _area, _entry)))
func clear() -> IntegrationResult:
	return IntegrationResult.new(_scope._host.RevokeSecret(_area, _entry))
