## Generated by Rookframe SDK 0.9.2. Regenerate with `rookframe facade`.
extends RefCounted

const ActorId = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/actor_id.gd")
var id: ActorId
var data: Variant
func _init(value: Dictionary) -> void:
	id = ActorId.new(value.id)
	data = value.data
