## Generated by Rookframe SDK 0.10.0. Regenerate with `rookframe facade`.
extends RefCounted

const ActorId = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/actor_id.gd")
var id: ActorId
var data: Variant
var access_level: String
func _init(value: Dictionary) -> void:
	id = ActorId.new(value.id)
	data = value.data
	access_level = value.access_level
