## Generated by Rookframe SDK 0.7.0. Regenerate with `rookframe facade`.
extends RefCounted
const ServiceScope = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/service_scope.gd")
const SecretEntry = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/secret_entry.gd")
const AuthenticationOperation = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/authentication_operation.gd")
const IntegrationOperation = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/integration_operation.gd")

var _scope: ServiceScope
var _name: String
func _init(scope: ServiceScope, name: String) -> void:
	_scope = scope
	_name = name
## Rookframe confirms Package, destination and purpose before opening any browser.
func sign_in(destination: SecretEntry) -> AuthenticationOperation:
	if destination._scope != _scope:
		return AuthenticationOperation.new(_scope, {"ok": false, "code": "scope_mismatch", "message": "Use a secret from this SDK scope."})
	return AuthenticationOperation.new(_scope, _scope._host.StartAuthentication(_name, destination._area, destination._entry))
func refresh(destination: SecretEntry) -> IntegrationOperation:
	if destination._scope != _scope:
		return IntegrationOperation.new(_scope, {"ok": false, "code": "scope_mismatch", "message": "Use a secret from this SDK scope."})
	return IntegrationOperation.new(_scope, _scope._host.RefreshSecret(_name, destination._area, destination._entry))
