## Generated by Rookframe SDK 0.9.2. Regenerate with `rookframe facade`.
extends RefCounted
const ServiceScope = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/service_scope.gd")
const IntegrationResult = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/integration_result.gd")
const TextResult = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/text_result.gd")

var _scope: ServiceScope
func _init(scope: ServiceScope) -> void:
	_scope = scope
func read_text() -> TextResult:
	return TextResult.new(_scope._host.ReadClipboard())
func write_text(text: String) -> IntegrationResult:
	return IntegrationResult.new(_scope._host.WriteClipboard(text))
