## Generated by Rookframe SDK 0.10.0. Regenerate with `rookframe facade`.
extends RefCounted

const Contribution = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/contribution.gd")
var _host: Object
var _slot: String

func _init(host: Object, slot: String) -> void:
	_host = host
	_slot = slot

## Append an authored contribution in Package-local order. Repeated scenes are idempotent.
func push(entry: Contribution) -> void:
	_host.RegisterContribution(_slot, entry.scene)
