## Generated by Rookframe SDK 0.9.2. Regenerate with `rookframe facade`.
extends RefCounted

const ContentReference = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/content_reference.gd")
const ContentKind = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/content_kind.gd")
var reference: ContentReference
var title: String
var kind: ContentKind.Value
var available: bool
func _init(value: Dictionary) -> void:
	reference = ContentReference.new(value.packageId, value.localId)
	title = value.displayName
	kind = ContentKind.Value.UNKNOWN
	available = value.available
	if value.type == "actor_definition":
		kind = ContentKind.Value.ACTOR_DEFINITION
	if value.type == "miniature":
		kind = ContentKind.Value.MINIATURE
	if value.type == "prop":
		kind = ContentKind.Value.PROP
	if value.type == "surface_finish":
		kind = ContentKind.Value.SURFACE_FINISH
	if value.type == "wall_style":
		kind = ContentKind.Value.WALL_STYLE
