## Generated by Rookframe SDK 0.8.0. Regenerate with `rookframe facade`.
extends RefCounted

const ContentReference = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/content_reference.gd")
const ContentEntryResult = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/content_entry_result.gd")
const ContentEntryListResult = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/content_entry_list_result.gd")
const ContentKind = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/content_kind.gd")

var _host: Object
func _init(host: Object) -> void:
	_host = host

func list(kind: ContentKind.Value = ContentKind.Value.ALL) -> ContentEntryListResult:
	return ContentEntryListResult.new(_host.ListContent(kind))
func read(reference: ContentReference) -> ContentEntryResult:
	return ContentEntryResult.new(_host.ReadContent(reference.package_id, reference.local_id))
