## Generated by Rookframe SDK 0.9.2. Regenerate with `rookframe facade`.
extends Resource

const FeedbackAction = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/feedback_action.gd")
@export var title: String
@export_multiline var message: String
@export var actions: Array[FeedbackAction] = []
