## Generated by Rookframe SDK 0.7.0. Regenerate with `rookframe facade`.
extends RefCounted
const ServiceScope = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/service_scope.gd")
const FileArea = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/file_area.gd")

const FileLocation = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/file_location.gd")
var _scope: ServiceScope
var _package: FileArea
var _user: FileArea
var _world: FileArea
var package: FileArea:
	get:
		return _package
var user: FileArea:
	get:
		return _user
var world: FileArea:
	get:
		return _world
func _init(scope: ServiceScope) -> void:
	_scope = scope
	_package = FileArea.new(scope, "package")
	_user = FileArea.new(scope, "user")
	_world = FileArea.new(scope, "world")
const InternalFileReference = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/internal_file_reference.gd")
const ScopedFile = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/scoped_file.gd")

func open(reference: InternalFileReference) -> ScopedFile:
	return ScopedFile.new(_scope, FileLocation.new()._text(reference.area), reference.name)
const InternalFolderReference = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/internal_folder_reference.gd")
const ScopedFolder = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/scoped_folder.gd")

func open_folder(reference: InternalFolderReference) -> ScopedFolder:
	return ScopedFolder.new(_scope, FileLocation.new()._text(reference.area), reference.name)
