## Generated by Rookframe SDK 0.7.0. Regenerate with `rookframe facade`.
extends RefCounted
const ServiceScope = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/service_scope.gd")
const ScopedFile = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/scoped_file.gd")
const ScopedFolder = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/scoped_folder.gd")

var _scope: ServiceScope
var _area: String
func _init(scope: ServiceScope, area: String) -> void:
	_scope = scope
	_area = area
## Relative names are validated by the host on each use. A value grants no new authority.
func file(relative_name: String) -> ScopedFile:
	return ScopedFile.new(_scope, _area, relative_name)
func folder(relative_name: String) -> ScopedFolder:
	return ScopedFolder.new(_scope, _area, relative_name)
const FileSelection = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/file_selection.gd")

func select_file() -> FileSelection:
	return FileSelection.new(_scope, _area, _scope._host.SelectFile(_area, false))
const FolderSelection = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/folder_selection.gd")

func select_folder() -> FolderSelection:
	return FolderSelection.new(_scope, _area, _scope._host.SelectFile(_area, true))
