## Generated by Rookframe SDK 0.7.0. Regenerate with `rookframe facade`.
extends RefCounted
enum Area { PACKAGE, USER, WORLD }
func _text(area: Area) -> String:
	if area == Area.PACKAGE:
		return "package"
	if area == Area.USER:
		return "user"
	if area == Area.WORLD:
		return "world"
	return ""
func _value(area: String) -> Area:
	if area == "package":
		return Area.PACKAGE
	if area == "world":
		return Area.WORLD
	return Area.USER
