## Generated by Rookframe SDK 0.7.0. Regenerate with `rookframe facade`.
extends RefCounted
const ServiceScope = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/service_scope.gd")
const PendingOperation = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/pending_operation.gd")
const ScopedFile = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/scoped_file.gd")
const FileSelectionResult = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/file_selection_result.gd")

var _pending: PendingOperation
var _scope: ServiceScope
var _area: String
var _selection: ScopedFile
func _init(scope: ServiceScope, area: String, started: Dictionary) -> void:
	_scope = scope
	_area = area
	_pending = PendingOperation.new(scope, started)
func poll() -> FileSelectionResult:
	var result: Dictionary = _pending._consume()
	if _selection == null and result.get("ready", true) and result.get("ok", false):
		_selection = ScopedFile.new(_scope, _area, result.get("text", ""))
	return FileSelectionResult.new(result, _selection)
