## Generated by Rookframe SDK 0.7.0. Regenerate with `rookframe facade`.
extends RefCounted
const ServiceScope = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/service_scope.gd")
const PendingOperation = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/pending_operation.gd")
const ScopedFolder = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/scoped_folder.gd")
const FolderSelectionResult = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/folder_selection_result.gd")

var _pending: PendingOperation
var _scope: ServiceScope
var _area: String
var _selection: ScopedFolder
func _init(scope: ServiceScope, area: String, started: Dictionary) -> void:
	_scope = scope
	_area = area
	_pending = PendingOperation.new(scope, started)
func poll() -> FolderSelectionResult:
	var result: Dictionary = _pending._consume()
	if _selection == null and result.get("ready", true) and result.get("ok", false):
		_selection = ScopedFolder.new(_scope, _area, result.get("text", ""))
	return FolderSelectionResult.new(result, _selection)
