## Generated by Rookframe SDK 0.7.0. Regenerate with `rookframe facade`.
extends RefCounted
enum Value { GET, POST, PUT, PATCH, DELETE, HEAD, OPTIONS }
func _text(value: Value) -> String:
	if value == Value.GET:
		return "GET"
	if value == Value.POST:
		return "POST"
	if value == Value.PUT:
		return "PUT"
	if value == Value.PATCH:
		return "PATCH"
	if value == Value.DELETE:
		return "DELETE"
	if value == Value.HEAD:
		return "HEAD"
	if value == Value.OPTIONS:
		return "OPTIONS"
	return ""
