## Generated by Rookframe SDK 0.8.0. Regenerate with `rookframe facade`.
extends Node

const SDK = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/package_sdk_facade.gd")
## Available during start() in an installed World.
var sdk: SDK


func _ready() -> void:
	if has_meta("rookframe_sdk"):
		sdk = SDK.new(get_meta("rookframe_sdk"))
		if not has_meta("rookframe_cleanup"):
			start()


## Override for Package setup. Godot owns the surrounding Node lifecycle.
func start() -> void:
	pass


func cleanup_world(completed: Callable) -> void:
	cleanup(SDK.Cleanup.new(completed))

## Override when this executable root has World-specific cleanup.
func cleanup(operation: SDK.Cleanup) -> void:
	operation.complete()


## Override with fixed, typed definitions assembled from authored Setting resources.
func describe_settings() -> SDK.SettingsRegistration:
	return SDK.SettingsRegistration.new()

## Inspect the complete staged scope. Do not perform World operations here.
func validate_settings(candidate: SDK.SettingsCandidate) -> SDK.SettingsValidation:
	return SDK.SettingsValidation.new()

## Called once for a new exact version, only when an older copy exists.
func migrate_settings(migration: SDK.SettingsMigration) -> SDK.SettingsValues:
	return migration

func _rookframe_settings_schema() -> Dictionary:
	return get_meta("rookframe_sdk").DescribeSettings(describe_settings())

func _rookframe_validate_settings(scope: int, values: Dictionary) -> String:
	return validate_settings(SDK.SettingsCandidate.new(scope, values)).message

func _rookframe_migrate_settings(scope: int, source: String, target: String, values: Dictionary) -> Dictionary:
	return migrate_settings(SDK.SettingsMigration.new(scope, source, target, values))._copy()
