## Generated by Rookframe SDK 0.9.1. Regenerate with `rookframe facade`.
extends Resource
const FileLocation = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/file_location.gd")

## Portable relative identity in this Package's current areas, never an OS path or grant.
@export var area: FileLocation.Area = FileLocation.Area.USER
@export var name: String
func _init(location: FileLocation.Area = FileLocation.Area.USER, relative_name: String = "") -> void:
	area = location
	name = relative_name
