## Generated by Rookframe SDK 0.9.0. Regenerate with `rookframe facade`.
extends "res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/setting.gd"
@export var default_value: int = 0
@export var minimum: int = -1000000
@export var maximum: int = 1000000
