## Generated by Rookframe SDK 0.7.0. Regenerate with `rookframe facade`.
extends RefCounted
const ServiceScope = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/service_scope.gd")
const PendingOperation = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/pending_operation.gd")
const IntegrationResult = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/integration_result.gd")

var _pending: PendingOperation
func _init(scope: ServiceScope, started: Dictionary) -> void:
	_pending = PendingOperation.new(scope, started)
func poll() -> IntegrationResult:
	return IntegrationResult.new(_pending._consume())
