## Generated by Rookframe SDK 0.8.0. Regenerate with `rookframe facade`.
extends RefCounted
const ServiceScope = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/service_scope.gd")
const HttpMethod = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/http_method.gd")
const RequestHeaders = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/request_headers.gd")
const ResponseResult = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/response_result.gd")
const Account = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/account.gd")

var _scope: ServiceScope
var _name: String
var _account: Account
func _init(scope: ServiceScope, name: String, account: Account = null) -> void:
	_scope = scope
	_name = name
	_account = account
func request(path: String, method: HttpMethod.Value = HttpMethod.Value.GET, body: String = "", headers: RequestHeaders = null) -> ResponseResult:
	var provider_headers: RequestHeaders = headers if headers != null else RequestHeaders.new()
	var started: Dictionary
	if _account == null:
		started = _scope._host.RequestServiceWithHeaders(_name, path, HttpMethod.new()._text(method), body, provider_headers._copy())
	elif _account._scope != _scope:
		started = {"ok": false, "code": "scope_mismatch", "message": "Use an account from this SDK scope."}
	else:
		started = _scope._host.RequestAccountService(_account._provider, _account._area, _account._entry, _name, path, HttpMethod.new()._text(method), body, provider_headers._copy(), _account.refresh_policy)

	return ResponseResult.new(await _scope._complete(started))
const StreamResult = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/stream_result.gd")
const ScopedStream = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/scoped_stream.gd")
const ScopedFile = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/scoped_file.gd")
const IntegrationResult = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/integration_result.gd")

func open_stream(path: String) -> StreamResult:
	var started: Dictionary
	if _account == null:
		started = _scope._host.OpenServiceStream(_name, path)
	elif _account._scope != _scope:
		started = {"ok": false, "code": "scope_mismatch", "message": "Use an account from this SDK scope."}
	else:
		started = _scope._host.OpenAccountStream(_account._provider, _account._area, _account._entry, _name, path, _account.refresh_policy)

	var result: Dictionary = await _scope._complete(started)
	var stream: ScopedStream
	if result.get("ok", false):
		stream = ScopedStream.new(_scope, result.get("id", 0))
	return StreamResult.new(result, stream)
func download(path: String, target: ScopedFile) -> IntegrationResult:
	if target._scope != _scope:
		return IntegrationResult.new({"ok": false, "code": "scope_mismatch", "message": "Use a file from this SDK scope."})
	var started: Dictionary
	if _account == null:
		started = _scope._host.DownloadFile(_name, path, target._area, target._path)
	elif _account._scope != _scope:
		started = {"ok": false, "code": "scope_mismatch", "message": "Use an account from this SDK scope."}
	else:
		started = _scope._host.DownloadAccountFile(_account._provider, _account._area, _account._entry, _name, path, target._area, target._path, _account.refresh_policy)

	return IntegrationResult.new(await _scope._complete(started))
func upload(path: String, source: ScopedFile, method: HttpMethod.Value = HttpMethod.Value.POST) -> ResponseResult:
	if source._scope != _scope:
		return ResponseResult.new({"ok": false, "code": "scope_mismatch", "message": "Use a file from this SDK scope."})
	var started: Dictionary
	if _account == null:
		started = _scope._host.UploadFile(_name, path, HttpMethod.new()._text(method), source._area, source._path)
	elif _account._scope != _scope:
		started = {"ok": false, "code": "scope_mismatch", "message": "Use an account from this SDK scope."}
	else:
		started = _scope._host.UploadAccountFile(_account._provider, _account._area, _account._entry, _name, path, HttpMethod.new()._text(method), source._area, source._path, _account.refresh_policy)

	return ResponseResult.new(await _scope._complete(started))
