## Generated by Rookframe SDK 0.7.0. Regenerate with `rookframe facade`.
extends RefCounted
const ServiceScope = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/service_scope.gd")
const HttpMethod = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/http_method.gd")
const RequestHeaders = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/request_headers.gd")
const RequestOperation = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/request_operation.gd")

var _scope: ServiceScope
var _name: String
func _init(scope: ServiceScope, name: String) -> void:
	_scope = scope
	_name = name
func request(path: String, method: HttpMethod.Value = HttpMethod.Value.GET, body: String = "", headers: RequestHeaders = null) -> RequestOperation:
	var provider_headers: RequestHeaders = headers if headers != null else RequestHeaders.new()
	return RequestOperation.new(_scope, _scope._host.RequestServiceWithHeaders(_name, path, HttpMethod.new()._text(method), body, provider_headers._copy()))
const StreamOperation = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/stream_operation.gd")
const ScopedFile = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/scoped_file.gd")
const IntegrationOperation = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/integration_operation.gd")

func open_stream(path: String) -> StreamOperation:
	return StreamOperation.new(_scope, _scope._host.OpenServiceStream(_name, path))
func download(path: String, target: ScopedFile) -> IntegrationOperation:
	if target._scope != _scope:
		return IntegrationOperation.new(_scope, {"ok": false, "code": "scope_mismatch", "message": "Use a file from this SDK scope."})
	return IntegrationOperation.new(_scope, _scope._host.DownloadFile(_name, path, target._area, target._path))
func upload(path: String, source: ScopedFile, method: HttpMethod.Value = HttpMethod.Value.POST) -> RequestOperation:
	if source._scope != _scope:
		return RequestOperation.new(_scope, {"ok": false, "code": "scope_mismatch", "message": "Use a file from this SDK scope."})
	return RequestOperation.new(_scope, _scope._host.UploadFile(_name, path, HttpMethod.new()._text(method), source._area, source._path))
