## Generated by Rookframe SDK 0.12.0. Regenerate with `rookframe facade`.
extends "res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/setting.gd"
@export var default_value: float = 0.0
@export var minimum: float = -1000000
@export var maximum: float = 1000000
