## Generated by Rookframe SDK 0.9.2. Regenerate with `rookframe facade`.
extends "res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/setting.gd"
const Setting = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/setting.gd")
@export var properties: Array[Setting] = []
