## Generated by Rookframe SDK 0.9.1. Regenerate with `rookframe facade`.
extends RefCounted

const Rail = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/rail.gd")
const Rails = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/rails.gd")
const WindowButton = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/window_button.gd")
const ExtensionSurface = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/extension_surface.gd")
const SDK_EDITION := "2029"
const MINIMUM_REVISION := 1

var _host: Object
var _rails: Rails
## Package-scoped access to the workspace Rails.
var rails: Rails:
	get:
		return _rails


func _init(host: Object) -> void:
	_host = host
	_service_scope = ServiceScope.new(host)
	_browser = Browser.new(_service_scope)
	_authentication = Authentication.new(_service_scope)
	_secrets = Secrets.new(_service_scope)
	_network = Network.new(_service_scope)
	_clipboard = Clipboard.new(_service_scope)
	_files = Files.new(_service_scope)
	_settings = Settings.new(host)
	_dice = UnavailableCapability.new(host)
	_dice.configure("dice")
	_targeting = UnavailableCapability.new(host)
	_targeting.configure("targeting")
	_builder = UnavailableCapability.new(host)
	_builder.configure("builder")
	_windows = Windows.new(host)
	_content = Content.new(host)
	_scenes = Scenes.new(host)
	_rooks = Rooks.new(host)
	_system_records = SystemRecords.new(host)
	_actors = Actors.new(host)
	_world_data = WorldData.new(host)
	_rails = Rails.new(host)
	_ui_root = ContributionSlot.new(host, "ui-root")
	_slots = Slots.new(host)
	_feedback = Feedback.new(host)
	_translations = Translations.new(host)


## Stable Package identity, independent of builds and installations.
func package_id() -> String:
	return _host.PackageId()


## Current admitted resource root for this Package.
func package_root() -> String:
	return _host.PackageRoot()


## Current desktop, tablet or phone Presentation experience.
func presentation_experience() -> DeviceExperience:
	return DeviceExperience.new(_host.PresentationDevice())

const Contribution = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/contribution.gd")
const ContributionSlot = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/contribution_slot.gd")
const Slots = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/slots.gd")
const Feedback = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/feedback.gd")
const FeedbackMessage = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/feedback_message.gd")
const FeedbackAction = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/feedback_action.gd")
const Translations = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/translations.gd")
const Cleanup = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/cleanup.gd")
const DeviceExperience = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/device_experience.gd")

var _ui_root: ContributionSlot
var ui_root: ContributionSlot:
	get:
		return _ui_root

var _slots: Slots
var slots: Slots:
	get:
		return _slots

var _feedback: Feedback
var feedback: Feedback:
	get:
		return _feedback

var _translations: Translations
var translations: Translations:
	get:
		return _translations

const OperationResult = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/operation_result.gd")
const DataResult = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/data_result.gd")
const WorldContext = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/world_context.gd")
const WorldData = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/world_data.gd")
const ContentReference = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/content_reference.gd")
const ActorDefinition = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/actor_definition.gd")
const UnavailableCapability = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/unavailable_capability.gd")
const ActorId = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/actor_id.gd")
const SystemRecordId = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/system_record_id.gd")
const RookId = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/rook_id.gd")
const SceneId = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/scene_id.gd")
const Actor = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/actor.gd")
const ActorResult = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/actor_result.gd")
const ActorListResult = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/actor_list_result.gd")
const SystemRecord = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/system_record.gd")
const SystemRecordResult = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/system_record_result.gd")
const SystemRecordListResult = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/system_record_list_result.gd")
const Rook = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/rook.gd")
const RookResult = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/rook_result.gd")
const RookListResult = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/rook_list_result.gd")
const Scene = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/scene.gd")
const SceneResult = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/scene_result.gd")
const ContentEntry = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/content_entry.gd")
const ContentEntryResult = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/content_entry_result.gd")
const ContentEntryListResult = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/content_entry_list_result.gd")
const Actors = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/actors.gd")
const SystemRecords = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/system_records.gd")
const Rooks = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/rooks.gd")
const DistanceResult = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/distance_result.gd")
const Scenes = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/scenes.gd")
const Content = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/content.gd")
const ContentKind = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/content_kind.gd")
const Windows = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/windows.gd")

func context() -> WorldContext:
	return WorldContext.new(_host.WorldContext())

var _world_data: WorldData
var world_data: WorldData:
	get:
		return _world_data

var _actors: Actors
var actors: Actors:
	get:
		return _actors

var _system_records: SystemRecords
var system_records: SystemRecords:
	get:
		return _system_records

var _rooks: Rooks
var rooks: Rooks:
	get:
		return _rooks

var _scenes: Scenes
var scenes: Scenes:
	get:
		return _scenes

var _content: Content
var content: Content:
	get:
		return _content

var _windows: Windows
var windows: Windows:
	get:
		return _windows

var _builder: UnavailableCapability
var builder: UnavailableCapability:
	get:
		return _builder

var _targeting: UnavailableCapability
var targeting: UnavailableCapability:
	get:
		return _targeting

var _dice: UnavailableCapability
var dice: UnavailableCapability:
	get:
		return _dice

const SettingsScope = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/settings_scope.gd")
const Setting = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/setting.gd")
const TextSetting = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/text_setting.gd")
const SecretSetting = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/secret_setting.gd")
const SettingsRegistration = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/settings_registration.gd")
const SettingsValidation = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/settings_validation.gd")
const ToggleSetting = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/toggle_setting.gd")
const IntegerSetting = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/integer_setting.gd")
const NumberSetting = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/number_setting.gd")
const ObjectSetting = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/object_setting.gd")
const ArraySetting = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/array_setting.gd")
const TextListSetting = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/text_list_setting.gd")
const TextList = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/text_list.gd")
const IntegerListSetting = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/integer_list_setting.gd")
const IntegerList = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/integer_list.gd")
const SettingsValues = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/settings_values.gd")
const SettingsDraft = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/settings_draft.gd")
const SettingsCandidate = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/settings_candidate.gd")
const SettingsMigration = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/settings_migration.gd")
const Settings = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/settings.gd")
const SettingsView = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/settings_view.gd")
const SettingsViewDefinition = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/settings_view_definition.gd")

var _settings: Settings
var settings: Settings:
	get:
		return _settings

const IntegrationResult = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/integration_result.gd")
const TextResult = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/text_result.gd")
const BytesResult = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/bytes_result.gd")
const Clipboard = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/clipboard.gd")
const Files = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/files.gd")
const FileArea = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/file_area.gd")
const ScopedFile = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/scoped_file.gd")
const ScopedFolder = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/scoped_folder.gd")
const ResponseResult = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/response_result.gd")
const ServiceDefinition = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/service_definition.gd")
const HttpMethod = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/http_method.gd")
const RequestHeaders = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/request_headers.gd")
const Network = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/network.gd")
const NamedService = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/named_service.gd")
const PortraitResult = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/portrait_result.gd")
const FileSelectionResult = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/file_selection_result.gd")
const FolderSelectionResult = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/folder_selection_result.gd")
const ScopedStream = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/scoped_stream.gd")
const StreamResult = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/stream_result.gd")
const FileLocation = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/file_location.gd")
const InternalFileReference = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/internal_file_reference.gd")
const InternalFolderReference = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/internal_folder_reference.gd")
const AuthenticationProviderDefinition = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/authentication_provider_definition.gd")
const SecretResult = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/secret_result.gd")
const ProviderTokens = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/provider_tokens.gd")
const ProviderTokenResult = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/provider_token_result.gd")
const Secrets = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/secrets.gd")
const SecretArea = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/secret_area.gd")
const SecretEntry = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/secret_entry.gd")
const Authentication = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/authentication.gd")
const AccountStatus = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/account_status.gd")
const Account = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/account.gd")
const Browser = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/browser.gd")
const ServiceScope = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/service_scope.gd")
var _service_scope: ServiceScope

var _files: Files
var files: Files:
	get:
		return _files

var _clipboard: Clipboard
var clipboard: Clipboard:
	get:
		return _clipboard

var _network: Network
var network: Network:
	get:
		return _network

var _secrets: Secrets
var secrets: Secrets:
	get:
		return _secrets

var _authentication: Authentication
var authentication: Authentication:
	get:
		return _authentication

var _browser: Browser
var browser: Browser:
	get:
		return _browser
