## Generated by Rookframe SDK 0.8.0. Regenerate with `rookframe facade`.
extends RefCounted
## Raw credentials are authorized for this owning Package's checked API requests.
var access_token: String
var token_type: String
var refresh_token: String
var scope: String
var has_expiry: bool
var expires_at: int
func _init(result: Dictionary) -> void:
	access_token = result.get("access_token", "")
	token_type = result.get("token_type", "")
	refresh_token = result.get("refresh_token", "")
	scope = result.get("scope", "")
	has_expiry = result.get("has_expiry", false)
	expires_at = result.get("expires_at", 0)
