## Generated by Rookframe SDK 0.7.0. Regenerate with `rookframe facade`.
extends RefCounted

const WindowButton = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/window_button.gd")
var _host: Object
var _side: String


func _init(host: Object, side: String) -> void:
	_host = host
	_side = side


## Add an authored window-opening entry in Package-local insertion order.
## Repeated registration of the same entry is idempotent in this Presentation.
## Rookframe owns opening, responsive placement, lifetime and diagnostics.
func push(entry: WindowButton) -> void:
	_host.RegisterWindowButton(_side, entry.button_scene, entry.window.scene)
