## Generated by Rookframe SDK 0.7.0. Regenerate with `rookframe facade`.
extends RefCounted
## Only these provider headers cross the checked destination boundary.
var authorization: String = ""
var accept: String = ""
var content_type: String = ""
var if_match: String = ""
var if_none_match: String = ""
var api_key: String = ""
func _copy() -> Dictionary:
	var headers: Dictionary = {}
	if not authorization.is_empty():
		headers["Authorization"] = authorization
	if not accept.is_empty():
		headers["Accept"] = accept
	if not content_type.is_empty():
		headers["Content-Type"] = content_type
	if not if_match.is_empty():
		headers["If-Match"] = if_match
	if not if_none_match.is_empty():
		headers["If-None-Match"] = if_none_match
	if not api_key.is_empty():
		headers["X-Api-Key"] = api_key
	return headers
