## Generated by Rookframe SDK 0.9.0. Regenerate with `rookframe facade`.
extends RefCounted

const RookId = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/rook_id.gd")
const ActorId = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/actor_id.gd")
const RookResult = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/rook_result.gd")
const RookListResult = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/rook_list_result.gd")
const SceneId = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/scene_id.gd")
const ContentReference = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/content_reference.gd")
const OperationResult = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/operation_result.gd")

var _host: Object
func _init(host: Object) -> void:
	_host = host

func list() -> RookListResult:
	return RookListResult.new(_host.ListRooks())
func read(id: RookId) -> RookResult:
	return RookResult.new(_host.ReadRook(id.value))
func create(miniature: ContentReference, scene: SceneId, position: Vector2, yaw: float = 0.0) -> RookResult:
	return RookResult.new(_host.CreateRook(miniature.package_id, miniature.local_id, scene.value, position, yaw))
func move(id: RookId, position: Vector2, yaw: float = 0.0) -> RookResult:
	return RookResult.new(_host.MoveRook(id.value, position, yaw))
func link(id: RookId, actor: ActorId) -> OperationResult:
	return OperationResult.new(_host.LinkRook(id.value, actor.value))
func unlink(id: RookId) -> OperationResult:
	return OperationResult.new(_host.UnlinkRook(id.value))
func delete(id: RookId) -> OperationResult:
	return OperationResult.new(_host.DeleteRook(id.value))
