## Generated by Rookframe SDK 0.10.0. Regenerate with `rookframe facade`.
extends RefCounted

const SceneId = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/scene_id.gd")
var id: SceneId
var name: String
func _init(value: Dictionary) -> void:
	id = SceneId.new(value.id)
	name = value.name
