## Generated by Rookframe SDK 0.12.0. Regenerate with `rookframe facade`.
extends RefCounted
const ServiceScope = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/service_scope.gd")
const SecretEntry = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/secret_entry.gd")
const SecretSetting = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/secret_setting.gd")

var _scope: ServiceScope
var _area: String
func _init(scope: ServiceScope, area: String) -> void:
	_scope = scope
	_area = area
func entry(name: String) -> SecretEntry:
	return SecretEntry.new(_scope, _area, name)
func setting(descriptor: SecretSetting) -> SecretEntry:
	return entry(descriptor.key)
