## Generated by Rookframe SDK 0.12.0. Regenerate with `rookframe facade`.
extends "res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/setting.gd"
## Values use the existing protected store and never enter an ordinary draft/copy.

const AuthenticationProviderDefinition = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/authentication_provider_definition.gd")
## Optional provider for Rookframe-owned sign-in/refresh/clear controls.
@export var authentication: AuthenticationProviderDefinition
