## Generated by Rookframe SDK 0.10.0. Regenerate with `rookframe facade`.
extends RefCounted
const ServiceScope = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/service_scope.gd")
const SecretArea = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/secret_area.gd")

var _user: SecretArea
var _world: SecretArea
var user: SecretArea:
	get:
		return _user
var world: SecretArea:
	get:
		return _world
func _init(scope: ServiceScope) -> void:
	_user = SecretArea.new(scope, "user")
	_world = SecretArea.new(scope, "world")
