## Generated by Rookframe SDK 0.7.0. Regenerate with `rookframe facade`.
extends RefCounted
## Internal Package binding shared by every typed integration value.
var _host: Object
func _init(host: Object) -> void:
	_host = host
