## Generated by Rookframe SDK 0.9.0. Regenerate with `rookframe facade`.
extends RefCounted
## Internal Package binding shared by every typed integration value.
var _host: Object
func _init(host: Object) -> void:
	_host = host
## Native signal ownership handles main-thread delivery and discards continuations at stop.
func _complete(started: Dictionary, authentication: bool = false) -> Dictionary:
	if started.get("ready", true):
		return started
	return await _host.ServiceCompletion(started.get("id", 0), authentication)
