## Generated by Rookframe SDK 0.9.1. Regenerate with `rookframe facade`.
extends "res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/settings_draft.gd"
const SettingsScope = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/settings_scope.gd")
var scope: SettingsScope.Kind
var source_version: String
var target_version: String
func _init(candidate_scope: SettingsScope.Kind, source: String, target: String, values: Dictionary) -> void:
	super(values)
	scope = candidate_scope
	source_version = source
	target_version = target
