## Generated by Rookframe SDK 0.10.0. Regenerate with `rookframe facade`.
extends RefCounted
const SettingsScope = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/settings_scope.gd")
const SettingsValues = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/settings_values.gd")
## Only the owning Package receives accepted-change notifications.
signal changed(scope: SettingsScope.Kind)
var _host: Object
func _init(host: Object) -> void:
	_host = host
	_host.connect("SettingsChanged", _changed)

func _changed(scope: int) -> void:
	changed.emit(scope)

var user: SettingsValues:
	get:
		return SettingsValues.new(_host.ReadPackageSettings(SettingsScope.Kind.USER, ""))
var world: SettingsValues:
	get:
		return SettingsValues.new(_host.ReadPackageSettings(SettingsScope.Kind.WORLD, ""))

## Read an Enabled Package's non-secret copy. No registration or service object is shared.
func read_other(package_id: String, scope: SettingsScope.Kind) -> SettingsValues:
	return SettingsValues.new(_host.ReadPackageSettings(scope, package_id))
