## Generated by Rookframe SDK 0.9.1. Regenerate with `rookframe facade`.
extends Resource
const Setting = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/setting.gd")
@export var user: Array[Setting] = []
@export var world: Array[Setting] = []
