## Generated by Rookframe SDK 0.12.0. Regenerate with `rookframe facade`.
extends "res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/settings_values.gd"
const SettingsScope = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/settings_scope.gd")
var scope: SettingsScope.Kind
func _init(candidate_scope: SettingsScope.Kind, values: Dictionary) -> void:
	super(values)
	scope = candidate_scope
