## Generated by Rookframe SDK 0.10.0. Regenerate with `rookframe facade`.
extends "res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/settings_values.gd"

func set_text(setting: TextSetting, value: String) -> void:
	_values[setting.key] = value

func set_toggle(setting: ToggleSetting, value: bool) -> void:
	_values[setting.key] = value

func set_integer(setting: IntegerSetting, value: int) -> void:
	_values[setting.key] = value

func set_number(setting: NumberSetting, value: float) -> void:
	_values[setting.key] = value

func set_object(setting: ObjectSetting, value: Dictionary) -> void:
	_values[setting.key] = value.duplicate(true)

func set_array(setting: ArraySetting, value: Array) -> void:
	_values[setting.key] = value.duplicate(true)

func set_text_list(setting: TextListSetting, value: TextList) -> void:
	_values[setting.key] = value._copy()

func set_integer_list(setting: IntegerListSetting, value: IntegerList) -> void:
	_values[setting.key] = value._copy()
