## Generated by Rookframe SDK 0.10.0. Regenerate with `rookframe facade`.
extends RefCounted

const SystemRecordId = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/system_record_id.gd")
var id: SystemRecordId
var type_name: String
var data: Variant
func _init(value: Dictionary) -> void:
	id = SystemRecordId.new(value.id)
	type_name = value.type_name
	data = value.data
