## Generated by Rookframe SDK 0.9.1. Regenerate with `rookframe facade`.
extends "res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/setting.gd"
@export var default_value: PackedStringArray = []
@export var minimum_items: int = 0
@export var maximum_items: int = 256
@export var minimum_length: int = 0
@export var maximum_length: int = 4096
