## Generated by Rookframe SDK 0.7.0. Regenerate with `rookframe facade`.
extends RefCounted
## A detached typed list. Mutations affect this draft helper only.
var _source: Array
var _added: Array = []
func _init(values: Array = []) -> void:
	_source = values.duplicate(true)
func size() -> int:
	return _source.size() + _added.size()
func is_empty() -> bool:
	return size() == 0
func at(index: int) -> String:
	var value: String = _source[index] if index < _source.size() else _added[index - _source.size()]
	return value
func append(value: String) -> void:
	_added.append(value)
func _copy() -> Array:
	var values: Array = []
	for index in range(size()):
		values.append(at(index))
	return values
