## Generated by Rookframe SDK 0.7.0. Regenerate with `rookframe facade`.
extends "res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/setting.gd"
@export var default_value: bool = false
