## Generated by Rookframe SDK 0.9.2. Regenerate with `rookframe facade`.
extends RefCounted

var _host: Object

func _init(host: Object) -> void:
	_host = host

## Translate within this Package's declared domain; missing messages retain their source text.
func text(message: String, domain: String = "default") -> String:
	return _host.Translate(message, domain)
