## Generated by Rookframe SDK 0.9.1. Regenerate with `rookframe facade`.
extends RefCounted

const OperationResult = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/operation_result.gd")

var _host: Object
func _init(host: Object) -> void:
	_host = host

var _capability: String
func configure(name: String) -> void:
	_capability = name
## Integration boundary reserved for the owning project; no predicted gameplay result.
func status() -> OperationResult:
	return OperationResult.new(_host.CapabilityStatus(_capability))
