## Generated by Rookframe SDK 0.12.0. Regenerate with `rookframe facade`.
extends Resource

const ExtensionSurface = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/extension_surface.gd")
## Authored Button scene, using the public UI Kit Theme and assets.
@export var button_scene: PackedScene
## The window to open when this entry is activated.
@export var window: ExtensionSurface
