## Generated by Rookframe SDK 0.10.0. Regenerate with `rookframe facade`.
extends RefCounted

const WorldCapability = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/world_capability.gd")
const ExtensionSurface = preload("res://rookframe/packages/9f64487d-5a09-48e0-8bdf-8071dd9ef882/sdk/extension_surface.gd")

var _host: Object
func _init(host: Object) -> void:
	_host = host

func open(surface: ExtensionSurface) -> void:
	_host.OpenWindow(surface.scene)
